[project]
name = "intrafact-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.5.0",
    "openai>=2.20.0",
    "sentence-transformers>=5.2.2",
]
